### ISSUE TITLE
Testing example misses 'input/MP7_alex_fc7_feat.mat'

### ISSUE THREAD

**Issue by washingtonsk8** [shuyueL/FFNet#1]
After running 'python nn_test.py' the following error occurs:
> FileNotFoundError: [Errno 2] No such file or directory: 'input/MP7_alex_fc7_feat.mat'

Is this file available, or we have to create it by ourselves?

**Comment by shuyueL** [comment]
Oh... it was not uploaded successfully as the size exceeded 25MB.  Now I get it uploaded in the input directory. Thanks.

**Comment by washingtonsk8** [comment]
It is ok now, thanks.
