### ISSUE TITLE
Get the performance number

### ISSUE THREAD

**Issue by brownwolf** [shuyueL/FFNet#2]
hi shuyue:
      I wan to know how to get the performance number as your paper say,does your code has evaluation parts？thanks!

**Comment by shuyueL** [comment]
Hi:
The evaluation metric is simply the segment-level coverage. You can implement it in any languages. A segment selected by a method is considered as true positive if the number of important frames it covers the ground truth labels exceeds a certain threshold called the hit number. For example, there is a video only has one segment of 30 frames and it is labeled as important (1 for all frames). Suppose our algorithm selects 10 frames of it, then when hit number <= 10, the coverage is 100%. When hit number > 10, the coverage is 0%. One thing to note that our algorithm takes the processed frames and their neighboring ones(with processed frames as window centroids, win size is equal to the win size in the reward design) as important subsets of the video.

**Comment by brownwolf** [comment]
thanks,i've got it,i will have a try.and may i download all your tour20 alex-fc7 feature,thanks!
