### ISSUE TITLE
Thank for Your works

### ISSUE THREAD

**Issue by zmxzsl** [shuyueL/FFNet#3]
I want to know whether the data required for training needs to be extract feature by network up front，saving file .mat？Thanks again.

**Comment by shuyueL** [comment]
Yes. the input of FFNet is a feature vector extracted from Alexnet.

**Comment by nikhileshva** [comment]
Also, is the feature vector for a single video file or for the entire dataset?

**Comment by shuyueL** [comment]
@nikhileshva The input is a feature vector of dimension 4096, which is extracted with a single frame.
