### ISSUE TITLE
Alexnet Architecture details

### ISSUE THREAD

**Issue by niti1405** [shuyueL/FFNet#4]
I want to know the Alexnet architecture details that you have used to extract the features from video frames. 
As you have mentioned in the white paper - "Alexnet fc7 features (4096-dimensional) to represent each video frame and tune the parameters in each method to have the best performance."

What are the parameter that you have tuned/changed?

**Comment by shuyueL** [comment]
@niti1405 We did not tune Alexnet. We tuned the parameters in the compared methods so that they had the best performance they were able to get.
